CREATE TABLE users (
 user_id                        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 username                       text NOT NULL UNIQUE,
 password                       text NOT NULL,
 user_xp                        integer NOT NULL DEFAULT 0,
 user_level                     integer NOT NULL DEFAULT 1,
 user_email                     text NULL,
 date_created                   timestamp NOT NULL DEFAULT now()
);

CREATE TABLE kobolds (
 kobold_id                      INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 user_id                        INTEGER REFERENCES users(user_id),
 kobold_name                    TEXT NOT NULL DEFAULT 'Kobold',
 kobold_level                   INTEGER NOT NULL DEFAULT 1,
 kobold_xp                      INTEGER NOT NULL DEFAULT 0,
 kobold_muscle                  INTEGER NOT NULL DEFAULT 0,
 kobold_fitness                 INTEGER NOT NULL DEFAULT 0,
 kobold_eloquence               integer NOT NULL DEFAULT 0,
 kobold_mana                    integer NOT NULL DEFAULT 0,
 kobold_intellect               integer NOT NULL DEFAULT 0,
 currency_wood_nickels          integer NOT NULL DEFAULT 0,
 currency_equipment_scraps      integer NOT NULL DEFAULT 0,
 currency_dragon_influence      integer NOT NULL DEFAULT 0,
 kobold_health                  integer NOT NULL DEFAULT 100,
 kobold_max_health              integer NOT NULL DEFAULT 100,
 kobold_energy                  integer NOT NULL DEFAULT 100,
 kobold_max_energy              integer NOT NULL DEFAULT 100,
 kobold_energy_used_last        TIMESTAMP DEFAULT NULL,
 adventure_xp_tally             integer NOT NULL DEFAULT 0,
 adventure_nickel_tally         integer NOT NULL DEFAULT 0,
 adventure_scrap_tally          integer NOT NULL DEFAULT 0,
 adventure_influence_tally      integer NOT NULL DEFAULT 0
);

CREATE TABLE locations (
 location_id                    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 location_name                  text NOT NULL,
 location_description           text NOT NULL,
 location_level                 integer NOT NULL
);

CREATE TABLE encounters (
 encounter_id                   integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 location_id                    integer REFERENCES locations(location_id) NOT NULL,
 encounter_name                 text NOT NULL,
 encounter_text                 text NOT NULL,
 encounter_level                integer NOT NULL,
 encounter_base_difficulty      integer NOT NULL,
 encounter_bonus_difficulty     integer NOT NULL DEFAULT 0,
 encounter_base_reward          integer NOT NULL,
 encounter_bonus_reward         integer NOT NULL DEFAULT 0
);

CREATE TABLE resolutions (
 id                             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 encounter_id                   integer REFERENCES encounters(encounter_id) NOT NULL,
 resolution_name                text NOT NULL,
 resolution_action              text NOT NULL,
 resolution_stat                text NOT NULL,
 resolution_success             text NOT NULL,
 resolution_fail                text NOT NULL
);


